# device
mode: train  # train sample
gpu_ids: [ 0, 1, 2, 3 ]  # gpu ids
batch_size: 1  # batch size each item denotes one story
num_workers: 4  # number of workers
num_cpu_cores: -1  # number of cpu cores
seed: 0  # random seed
# ckpt_dir: /path/to/save_ckpt # checkpoint directory
ckpt_dir: /lustre/S/yuxiaoyi/device/save_ckpt # checkpoint directory
run_name: 4.1_new_text # name for this run

# task
dataset: oxford  # pororo flintstones vistsis vistdii
task: continuation  # continuation visualization

# train
init_lr: 1e-5  # initial learning rate
warmup_epochs: 1  # warmup epochs
max_epochs: 10  # max epochs
train_model_file: null # model file for resume, none for train from scratch
freeze_clip: True  # whether to freeze clip
freeze_blip: True  # whether to freeze blip
freeze_resnet: True  # whether to freeze resnet

# sample
test_model_file: /lustre/S/yuxiaoyi/device/save_ckpt/4.1_new_text/last.ckpt # model file for test
calculate_fid: True  # whether to calculate FID scores
scheduler: ddim  # ddim pndm
guidance_scale: 6  # guidance scale
num_inference_steps: 250  # number of inference steps
# sample_output_dir: /path/to/save_samples # output directory
sample_output_dir: /lustre/S/yuxiaoyi/sample/4.1_new_text # output directory

oxford:
  hdf5_file: /lustre/S/yuxiaoyi/oxford_data/oxford.hdf5
  max_length: 197  # 依据报错信息设置为197
  new_tokens: null # 主要人物的名字
  clip_embedding_tokens: null # 新增加了new_tokens后需要resize clip_embedding_tokens的长度
  blip_embedding_tokens: null # 新增加了new_tokens后需要resize blip_embedding_tokens的长度

# oxford:
#   hdf5_file: /lustre/S/yuxiaoyi/oxford_data/oxford.hdf5
#   max_length: 483  # 依据报错信息设置为484
#   new_tokens: ["biff", "chip", "kipper", "floppy", "nadim", "anneena", "wilf"] # 主要人物的名字
#   clip_embedding_tokens: 49414 # vocab.json中49408个单词。如果new tokens中有n个单词不存在 或者 仅有带\w的形式，则clip_embedding_tokens+n
#   blip_embedding_tokens: 30529 # 30522+n+2

hydra:
  run:
    dir: .
  output_subdir: /lustre/S/yuxiaoyi/logs
hydra/job_logging: enabled
hydra/hydra_logging: enabled
